---
- name: Create index file on web1 server
  hosts: web11
  become: yes


  tasks:
    - name: Create index.html file if not exist
      file:
        path: /var/www/html/index.html
        state: touch


    - name: Put content to /var/www/html/
      copy:
        content: |
          <h1 style="background-color:DodgerBlue;">Finding Nemo</h1>
          <h3>Web server 111 / CentOS 8</h3>
          <img src="https://facts.net/wp-content/uploads/2023/06/41-facts-about-the-movie-finding-nemo-1687347016.jpeg">
        dest: /var/www/html/index.html


    - name: Make sure file is existing
      file:
        path: /var/www/html/index.html
        state: file


    - name: Set ownership and permissions for index.html file 
      file:
        path : /var/www/html/index.html 
        owner : apache 
        group : apache 
        mode : '0644'
